
# Build all product STLs
all:
	$(MAKE) -C collections/collection-1-bambu-mods/filament-spool/scripts all

clean:
	$(MAKE) -C collections/collection-1-bambu-mods/filament-spool/scripts clean
.PHONY: all clean
