name: docs-checks
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Glossary check
        run: make glossary-check
